spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration/pg
  #            hibernate.jdbc.lob.non_contextual_creation=true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=kolumarket
    username: postgres
    password: password
  jpa:
    database: POSTGRESQL
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop #validate
        jdbc:
          lob:
            non_contextual_creation: true
  database:
    driverClassName: org.postgresql.Driver