spring:
  application:
    name: apigateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 5555
#  servlet:
#    context-path: /gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# http"//localhost:5555/gateway[/endpoint/]


