spring:
  application:
    name: zuul-server
server:
  port: 5555
  servlet:
    context-path: /gateway
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# http"//localhost:5555/gateway[/endpoint/]
zuul:
#  prefix: /gateway
  routes:
    auth:
      path: /auth/**
      serviceId: auth-service
    order:
      path: /order/**
      serviceId: order-service
    product:
      path: /product/**
      serviceId: product-service
    warehouse:
      path: /warehouse/**
      serviceId: warehouse-service

  sensitiveHeaders: Cookie, Set-Cookie

ribbon:
  eureka:
    enabled: true
